<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>fun.fengwk.convention4j</groupId>
    <artifactId>convention4j-parent</artifactId>
    <version>1.2.1</version>
  </parent>
  <groupId>fun.fengwk.opencli-hub</groupId>
  <artifactId>opencli-hub-parent</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>
  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <project.build.sourceEncoding>utf-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>utf-8</project.reporting.outputEncoding>
    <opencli-hub.version>1.0.0</opencli-hub.version>
    <gateway.version>1.0.8</gateway.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>fun.fengwk.opencli-hub</groupId>
        <artifactId>opencli-hub-share</artifactId>
        <version>${opencli-hub.version}</version>
      </dependency>
      <dependency>
        <groupId>fun.fengwk.opencli-hub</groupId>
        <artifactId>opencli-hub-core</artifactId>
        <version>${opencli-hub.version}</version>
      </dependency>
      <dependency>
        <groupId>fun.fengwk.opencli-hub</groupId>
        <artifactId>opencli-hub-infra</artifactId>
        <version>${opencli-hub.version}</version>
      </dependency>
      <dependency>
        <groupId>fun.fengwk.opencli-hub</groupId>
        <artifactId>opencli-hub-web</artifactId>
        <version>${opencli-hub.version}</version>
      </dependency>
      <dependency>
        <groupId>fun.fengwk.gateway</groupId>
        <artifactId>gateway-share</artifactId>
        <version>${gateway.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <modules>
    <module>share</module>
    <module>core</module>
    <module>infra</module>
    <module>web</module>
  </modules>
</project>
