package fun.fengwk.openclihub.share.constant;

import fun.fengwk.convention4j.api.code.DomainConventionErrorCodeEnumAdapter;
import fun.fengwk.convention4j.api.code.HttpStatus;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Stable OpenCLI Hub domain error codes.
 *
 * @author fengwk
 */
@AllArgsConstructor
@Getter
public enum HubErrorCodes implements DomainConventionErrorCodeEnumAdapter {

    INSTANCE_NOT_FOUND(HttpStatus.NOT_FOUND),
    INSTANCE_CODE_CONFLICT(HttpStatus.CONFLICT),
    INSTANCE_ARGUMENT_INVALID(HttpStatus.BAD_REQUEST),
    INSTANCE_BUSY(HttpStatus.CONFLICT),
    INSTANCE_NOT_RUNNING(HttpStatus.BAD_REQUEST),
    INSTANCE_WEBSITE_NOT_ENABLED(HttpStatus.BAD_REQUEST),
    INSTANCE_QUEUE_FULL(HttpStatus.TOO_MANY_REQUESTS),
    INSTANCE_QUEUE_CLEARED(HttpStatus.CONFLICT),
    CLIENT_DISCONNECTED(HttpStatus.BAD_REQUEST),
    INSTANCE_CONTEXT_NOT_CONNECTED(HttpStatus.BAD_REQUEST),
    INSTANCE_START_FAILED(HttpStatus.INTERNAL_SERVER_ERROR),
    INSTANCE_STOP_FAILED(HttpStatus.INTERNAL_SERVER_ERROR),
    INSTANCE_DELETE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR),
    INSTANCE_RUNTIME_NOT_FOUND(HttpStatus.NOT_FOUND),
    INSTANCE_VNC_UNAVAILABLE(HttpStatus.BAD_REQUEST),
    CONTEXT_ID_AMBIGUOUS(HttpStatus.CONFLICT),
    CONTEXT_ID_CONFLICT(HttpStatus.CONFLICT),
    EXTENSION_CONNECT_TIMEOUT(HttpStatus.REQUEST_TIMEOUT),
    NO_INSTANCE_AVAILABLE(HttpStatus.BAD_REQUEST),

    SETTINGS_ARGUMENT_INVALID(HttpStatus.BAD_REQUEST),
    SETTINGS_UPDATE_CONFLICT(HttpStatus.CONFLICT),

    OPENCLI_COMMAND_NOT_FOUND(HttpStatus.NOT_FOUND),
    OPENCLI_COMMAND_NOT_PUBLIC(HttpStatus.BAD_REQUEST),
    OPENCLI_COMMAND_BLACKLISTED(HttpStatus.BAD_REQUEST),
    OPENCLI_ARGUMENT_NOT_ALLOWED(HttpStatus.BAD_REQUEST),
    OPENCLI_ARGUMENT_INVALID(HttpStatus.BAD_REQUEST),
    OPENCLI_RESERVED_ARGUMENT(HttpStatus.BAD_REQUEST),
    OPENCLI_LOCAL_PATH_NOT_ALLOWED(HttpStatus.BAD_REQUEST),
    OPENCLI_RESOURCE_OUTPUT_ARGUMENT_MANAGED(HttpStatus.BAD_REQUEST),
    OPENCLI_OUTPUT_RULE_ARGUMENT_NOT_FOUND(HttpStatus.BAD_REQUEST),
    OPENCLI_RESOURCE_OUTPUT_RULE_INVALID(HttpStatus.BAD_REQUEST),

    EXECUTION_NOT_FOUND(HttpStatus.NOT_FOUND),
    INVALID_EXECUTION_REQUEST(HttpStatus.BAD_REQUEST),
    EXECUTION_TIMEOUT_OUT_OF_RANGE(HttpStatus.BAD_REQUEST),
    QUEUE_WAIT_TIMEOUT(HttpStatus.REQUEST_TIMEOUT),
    OPENCLI_EXECUTION_TIMEOUT(HttpStatus.REQUEST_TIMEOUT),
    OPENCLI_EXECUTION_FAILED(HttpStatus.INTERNAL_SERVER_ERROR),
    OPENCLI_INVALID_JSON_OUTPUT(HttpStatus.INTERNAL_SERVER_ERROR),
    EXECUTION_PERSIST_FAILED(HttpStatus.INTERNAL_SERVER_ERROR),

    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND),
    RESOURCE_PATH_INVALID(HttpStatus.BAD_REQUEST),
    RESOURCE_IN_USE(HttpStatus.CONFLICT),
    RESOURCE_UPLOAD_TOO_LARGE(HttpStatus.PAYLOAD_TOO_LARGE),
    RESOURCE_DELETE_FAILED(HttpStatus.INTERNAL_SERVER_ERROR),

    INSTANCE_LOG_SOURCE_INVALID(HttpStatus.BAD_REQUEST),
    LOG_FILE_NOT_FOUND(HttpStatus.NOT_FOUND),

    PLUGIN_SOURCE_NOT_FOUND(HttpStatus.NOT_FOUND),
    PLUGIN_SOURCE_ARGUMENT_INVALID(HttpStatus.BAD_REQUEST),
    PLUGIN_SOURCE_NAME_CONFLICT(HttpStatus.CONFLICT),
    PLUGIN_SOURCE_UPDATE_CONFLICT(HttpStatus.CONFLICT),
    PLUGIN_SYNC_BUSY(HttpStatus.CONFLICT),
    PLUGIN_SYNC_FAILED(HttpStatus.INTERNAL_SERVER_ERROR),
    PLUGIN_CLI_FAILED(HttpStatus.INTERNAL_SERVER_ERROR);

    private final HttpStatus httpStatus;

    @Override
    public String getDomain() {
        return "HUB";
    }

}
